/* eslint-disable @typescript-eslint/no-unsafe-member-access */
const firebase = require('firebase');
// Required for side-effects
require('firebase/firestore');

// Initialize Cloud Firestore through Firebase
firebase.initializeApp({
  apiKey: 'AIzaSyBn0IMRFzxed4Eq_3yifffn81wazUB7zvA',
  projectId: 'dinojuice-26ea5'
});

const db = firebase.firestore();

const bolDetail = [
    {
        "Store_Number": 366,
        "Bol_Number": "908741",
        "Delivery_Entry_ID": 2021080101,
        "Delivery_Date": "2021-08-01T02:31:53",
        "Loading_Date": "2021-08-01T01:44:00",
        "Split_Load_Store": 0,
        "Driver_Name": "YLARIA FLORES",
        "Driver_Id": 8147,
        "Carrier_Id": 3003,
        "Carrier_Name": "United Petroleum Transport                        ",
        "Terminal_Id": 1634,
        "Terminal_Name": "Phillips66 - Wichita, KS North          ",
        "Vendor_Id": 11362,
        "Vendor_Name": "Phillips66 Contract                               ",
        "Tractor": "2811",
        "Trailer": "882",
        "Bol_Detail": [
            {
                "EPA_Tank_id": 0,
                "Physical_Tanks": "1,2",
                "Product": "UNLEADED",
                "Pricing_Grade": 45,
                "Pricing_Grade_Name": "UNL 87 CONV 10% ETH",
                "Qt_Grade": 2,
                "Beg_Inches": "61.67|62.64",
                "End_Inches": "81.56|75.63",
                "Beg_Gallons": 21066,
                "End_Gallons": 28082,
                "Beg_Console": 44,
                "End_Console": 75,
                "Delivery_Gallons": 7016,
                "Sales_Gallons": 31,
                "Sales_During": 7016,
                "Gross": 7002,
                "Net": 6928,
                "Actual": 7047,
                "Variance": 45,
                "Date_Stamp": "2021-08-01T02:53:53"
            },
            {
                "EPA_Tank_id": 0,
                "Physical_Tanks": "3",
                "Product": "PREMIUM",
                "Pricing_Grade": 47,
                "Pricing_Grade_Name": "PRE 91 CONV 10% ETH",
                "Qt_Grade": 5,
                "Beg_Inches": "36.56",
                "End_Inches": "51.93",
                "Beg_Gallons": 2498,
                "End_Gallons": 4007,
                "Beg_Console": 35,
                "End_Console": 35,
                "Delivery_Gallons": 1509,
                "Sales_Gallons": 0,
                "Sales_During": 1509,
                "Gross": 1500,
                "Net": 1480,
                "Actual": 1509,
                "Variance": 9,
                "Date_Stamp": "2021-08-01T02:53:53"
            }
        ]
    },
    {
        "Store_Number": 366,
        "Bol_Number": "908741",
        "Delivery_Entry_ID": 2021080101,
        "Delivery_Date": "2021-08-01T02:31:53",
        "Loading_Date": "2021-08-01T01:44:00",
        "Split_Load_Store": 0,
        "Driver_Name": "YLARIA FLORES",
        "Driver_Id": 8147,
        "Carrier_Id": 3003,
        "Carrier_Name": "United Petroleum Transport                        ",
        "Terminal_Id": 1634,
        "Terminal_Name": "Phillips66 - Wichita, KS North          ",
        "Vendor_Id": 11362,
        "Vendor_Name": "Phillips66 Contract                               ",
        "Tractor": "2811",
        "Trailer": "882",
        "Bol_Detail": [
            {
                "EPA_Tank_id": 0,
                "Physical_Tanks": "1,2",
                "Product": "UNLEADED",
                "Pricing_Grade": 45,
                "Pricing_Grade_Name": "UNL 87 CONV 10% ETH",
                "Qt_Grade": 2,
                "Beg_Inches": "61.67|62.64",
                "End_Inches": "81.56|75.63",
                "Beg_Gallons": 21066,
                "End_Gallons": 28082,
                "Beg_Console": 44,
                "End_Console": 75,
                "Delivery_Gallons": 7016,
                "Sales_Gallons": 31,
                "Sales_During": 7016,
                "Gross": 7002,
                "Net": 6928,
                "Actual": 7047,
                "Variance": 45,
                "Date_Stamp": "2021-08-01T02:53:53"
            },
            {
                "EPA_Tank_id": 0,
                "Physical_Tanks": "3",
                "Product": "PREMIUM",
                "Pricing_Grade": 47,
                "Pricing_Grade_Name": "PRE 91 CONV 10% ETH",
                "Qt_Grade": 5,
                "Beg_Inches": "36.56",
                "End_Inches": "51.93",
                "Beg_Gallons": 2498,
                "End_Gallons": 4007,
                "Beg_Console": 35,
                "End_Console": 35,
                "Delivery_Gallons": 1509,
                "Sales_Gallons": 0,
                "Sales_During": 1509,
                "Gross": 1500,
                "Net": 1480,
                "Actual": 1509,
                "Variance": 9,
                "Date_Stamp": "2021-08-01T02:53:53"
            }
        ]
    },
    {
        "Store_Number": 366,
        "Bol_Number": "742138",
        "Delivery_Entry_ID": 2021080201,
        "Delivery_Date": "2021-08-02T10:52:00",
        "Loading_Date": "2021-08-02T09:51:00",
        "Split_Load_Store": 0,
        "Driver_Name": "CJ Brengman",
        "Driver_Id": 1765,
        "Carrier_Id": 3003,
        "Carrier_Name": "United Petroleum Transport                        ",
        "Terminal_Id": 153,
        "Terminal_Name": "Magellan - Valley Center, KS            ",
        "Vendor_Id": 11420,
        "Vendor_Name": "QT Fuels Inventory                                ",
        "Tractor": "9999",
        "Trailer": "9999",
        "Bol_Detail": [
            {
                "EPA_Tank_id": 0,
                "Physical_Tanks": "1,2",
                "Product": "UNLEADED",
                "Pricing_Grade": 45,
                "Pricing_Grade_Name": "UNL 87 CONV 10% ETH",
                "Qt_Grade": 2,
                "Beg_Inches": "56.67|57.37",
                "End_Inches": "65.97|75.2",
                "Beg_Gallons": 18801,
                "End_Gallons": 24711,
                "Beg_Console": 1943,
                "End_Console": 2074,
                "Delivery_Gallons": 5910,
                "Sales_Gallons": 131,
                "Sales_During": 5910,
                "Gross": 6004,
                "Net": 5937,
                "Actual": 6041,
                "Variance": 37,
                "Date_Stamp": "2021-08-02T10:52:00"
            },
            {
                "EPA_Tank_id": 0,
                "Physical_Tanks": "3",
                "Product": "PREMIUM",
                "Pricing_Grade": 47,
                "Pricing_Grade_Name": "PRE 91 CONV 10% ETH",
                "Qt_Grade": 5,
                "Beg_Inches": "34.84",
                "End_Inches": "60.2",
                "Beg_Gallons": 2338,
                "End_Gallons": 4853,
                "Beg_Console": 241,
                "End_Console": 247,
                "Delivery_Gallons": 2515,
                "Sales_Gallons": 6,
                "Sales_During": 2515,
                "Gross": 2501,
                "Net": 2472,
                "Actual": 2521,
                "Variance": 20,
                "Date_Stamp": "2021-08-02T10:52:00"
            }
        ]
    },
    {
        "Store_Number": 366,
        "Bol_Number": "742138",
        "Delivery_Entry_ID": 2021080201,
        "Delivery_Date": "2021-08-02T10:52:00",
        "Loading_Date": "2021-08-02T09:51:00",
        "Split_Load_Store": 0,
        "Driver_Name": "CJ Brengman",
        "Driver_Id": 1765,
        "Carrier_Id": 3003,
        "Carrier_Name": "United Petroleum Transport                        ",
        "Terminal_Id": 153,
        "Terminal_Name": "Magellan - Valley Center, KS            ",
        "Vendor_Id": 11420,
        "Vendor_Name": "QT Fuels Inventory                                ",
        "Tractor": "9999",
        "Trailer": "9999",
        "Bol_Detail": [
            {
                "EPA_Tank_id": 0,
                "Physical_Tanks": "1,2",
                "Product": "UNLEADED",
                "Pricing_Grade": 45,
                "Pricing_Grade_Name": "UNL 87 CONV 10% ETH",
                "Qt_Grade": 2,
                "Beg_Inches": "56.67|57.37",
                "End_Inches": "65.97|75.2",
                "Beg_Gallons": 18801,
                "End_Gallons": 24711,
                "Beg_Console": 1943,
                "End_Console": 2074,
                "Delivery_Gallons": 5910,
                "Sales_Gallons": 131,
                "Sales_During": 5910,
                "Gross": 6004,
                "Net": 5937,
                "Actual": 6041,
                "Variance": 37,
                "Date_Stamp": "2021-08-02T10:52:00"
            },
            {
                "EPA_Tank_id": 0,
                "Physical_Tanks": "3",
                "Product": "PREMIUM",
                "Pricing_Grade": 47,
                "Pricing_Grade_Name": "PRE 91 CONV 10% ETH",
                "Qt_Grade": 5,
                "Beg_Inches": "34.84",
                "End_Inches": "60.2",
                "Beg_Gallons": 2338,
                "End_Gallons": 4853,
                "Beg_Console": 241,
                "End_Console": 247,
                "Delivery_Gallons": 2515,
                "Sales_Gallons": 6,
                "Sales_During": 2515,
                "Gross": 2501,
                "Net": 2472,
                "Actual": 2521,
                "Variance": 20,
                "Date_Stamp": "2021-08-02T10:52:00"
            }
        ]
    },
    {
        "Store_Number": 366,
        "Bol_Number": "742184",
        "Delivery_Entry_ID": 2021080202,
        "Delivery_Date": "2021-08-02T18:17:23",
        "Loading_Date": "2021-08-02T17:46:00",
        "Split_Load_Store": 0,
        "Driver_Name": "Jen Hawley",
        "Driver_Id": 7064,
        "Carrier_Id": 3003,
        "Carrier_Name": "United Petroleum Transport                        ",
        "Terminal_Id": 153,
        "Terminal_Name": "Magellan - Valley Center, KS            ",
        "Vendor_Id": 11420,
        "Vendor_Name": "QT Fuels Inventory                                ",
        "Tractor": "9999",
        "Trailer": "9999",
        "Bol_Detail": [
            {
                "EPA_Tank_id": 0,
                "Physical_Tanks": "4",
                "Product": "DIESEL-AUTO",
                "Pricing_Grade": 8,
                "Pricing_Grade_Name": "ULSD #2 CLEAR - DIESEL",
                "Qt_Grade": 13,
                "Beg_Inches": "16.1",
                "End_Inches": "60.7",
                "Beg_Gallons": 1371,
                "End_Gallons": 8328,
                "Beg_Console": 533,
                "End_Console": 565,
                "Delivery_Gallons": 6957,
                "Sales_Gallons": 32,
                "Sales_During": 6957,
                "Gross": 7001,
                "Net": 6934,
                "Actual": 6989,
                "Variance": -12,
                "Date_Stamp": "2021-08-02T18:44:57"
            }
        ]
    },
    {
        "Store_Number": 366,
        "Bol_Number": "908948",
        "Delivery_Entry_ID": 2021080301,
        "Delivery_Date": "2021-08-03T13:11:23",
        "Loading_Date": "2021-08-03T12:50:00",
        "Split_Load_Store": 0,
        "Driver_Name": "Dave Watts",
        "Driver_Id": 311,
        "Carrier_Id": 3003,
        "Carrier_Name": "United Petroleum Transport                        ",
        "Terminal_Id": 1634,
        "Terminal_Name": "Phillips66 - Wichita, KS North          ",
        "Vendor_Id": 11362,
        "Vendor_Name": "Phillips66 Contract                               ",
        "Tractor": "2747",
        "Trailer": "1027",
        "Bol_Detail": [
            {
                "EPA_Tank_id": 0,
                "Physical_Tanks": "1,2",
                "Product": "UNLEADED",
                "Pricing_Grade": 45,
                "Pricing_Grade_Name": "UNL 87 CONV 10% ETH",
                "Qt_Grade": 2,
                "Beg_Inches": "50.01|50.76",
                "End_Inches": "66.1|73.08",
                "Beg_Gallons": 15884,
                "End_Gallons": 24292,
                "Beg_Console": 2986,
                "End_Console": 3091,
                "Delivery_Gallons": 8408,
                "Sales_Gallons": 105,
                "Sales_During": 8408,
                "Gross": 8501,
                "Net": 8406,
                "Actual": 8513,
                "Variance": 12,
                "Date_Stamp": "2021-08-03T13:30:46"
            }
        ]
    },
    {
        "Store_Number": 366,
        "Bol_Number": "742382",
        "Delivery_Entry_ID": 2021080401,
        "Delivery_Date": "2021-08-04T14:52:02",
        "Loading_Date": "2021-08-04T14:21:00",
        "Split_Load_Store": 0,
        "Driver_Name": "Dave Watts",
        "Driver_Id": 311,
        "Carrier_Id": 3003,
        "Carrier_Name": "United Petroleum Transport                        ",
        "Terminal_Id": 153,
        "Terminal_Name": "Magellan - Valley Center, KS            ",
        "Vendor_Id": 11420,
        "Vendor_Name": "QT Fuels Inventory                                ",
        "Tractor": "20747",
        "Trailer": "1027",
        "Bol_Detail": [
            {
                "EPA_Tank_id": 0,
                "Physical_Tanks": "1,2",
                "Product": "UNLEADED",
                "Pricing_Grade": 45,
                "Pricing_Grade_Name": "UNL 87 CONV 10% ETH",
                "Qt_Grade": 2,
                "Beg_Inches": "50.97|51.72",
                "End_Inches": "66.84|67.33",
                "Beg_Gallons": 16303,
                "End_Gallons": 23219,
                "Beg_Console": 3742,
                "End_Console": 3902,
                "Delivery_Gallons": 6916,
                "Sales_Gallons": 160,
                "Sales_During": 6916,
                "Gross": 7004,
                "Net": 6893,
                "Actual": 7076,
                "Variance": 72,
                "Date_Stamp": "2021-08-04T15:08:20"
            },
            {
                "EPA_Tank_id": 0,
                "Physical_Tanks": "3",
                "Product": "PREMIUM",
                "Pricing_Grade": 47,
                "Pricing_Grade_Name": "PRE 91 CONV 10% ETH",
                "Qt_Grade": 5,
                "Beg_Inches": "35.68",
                "End_Inches": "51.09",
                "Beg_Gallons": 2416,
                "End_Gallons": 3922,
                "Beg_Console": 483,
                "End_Console": 485,
                "Delivery_Gallons": 1506,
                "Sales_Gallons": 2,
                "Sales_During": 1506,
                "Gross": 1500,
                "Net": 1475,
                "Actual": 1508,
                "Variance": 8,
                "Date_Stamp": "2021-08-04T15:08:21"
            }
        ]
    },
    {
        "Store_Number": 366,
        "Bol_Number": "742382",
        "Delivery_Entry_ID": 2021080401,
        "Delivery_Date": "2021-08-04T14:52:02",
        "Loading_Date": "2021-08-04T14:21:00",
        "Split_Load_Store": 0,
        "Driver_Name": "Dave Watts",
        "Driver_Id": 311,
        "Carrier_Id": 3003,
        "Carrier_Name": "United Petroleum Transport                        ",
        "Terminal_Id": 153,
        "Terminal_Name": "Magellan - Valley Center, KS            ",
        "Vendor_Id": 11420,
        "Vendor_Name": "QT Fuels Inventory                                ",
        "Tractor": "20747",
        "Trailer": "1027",
        "Bol_Detail": [
            {
                "EPA_Tank_id": 0,
                "Physical_Tanks": "1,2",
                "Product": "UNLEADED",
                "Pricing_Grade": 45,
                "Pricing_Grade_Name": "UNL 87 CONV 10% ETH",
                "Qt_Grade": 2,
                "Beg_Inches": "50.97|51.72",
                "End_Inches": "66.84|67.33",
                "Beg_Gallons": 16303,
                "End_Gallons": 23219,
                "Beg_Console": 3742,
                "End_Console": 3902,
                "Delivery_Gallons": 6916,
                "Sales_Gallons": 160,
                "Sales_During": 6916,
                "Gross": 7004,
                "Net": 6893,
                "Actual": 7076,
                "Variance": 72,
                "Date_Stamp": "2021-08-04T15:08:20"
            },
            {
                "EPA_Tank_id": 0,
                "Physical_Tanks": "3",
                "Product": "PREMIUM",
                "Pricing_Grade": 47,
                "Pricing_Grade_Name": "PRE 91 CONV 10% ETH",
                "Qt_Grade": 5,
                "Beg_Inches": "35.68",
                "End_Inches": "51.09",
                "Beg_Gallons": 2416,
                "End_Gallons": 3922,
                "Beg_Console": 483,
                "End_Console": 485,
                "Delivery_Gallons": 1506,
                "Sales_Gallons": 2,
                "Sales_During": 1506,
                "Gross": 1500,
                "Net": 1475,
                "Actual": 1508,
                "Variance": 8,
                "Date_Stamp": "2021-08-04T15:08:21"
            }
        ]
    },
    {
        "Store_Number": 366,
        "Bol_Number": "909076",
        "Delivery_Entry_ID": 2021080501,
        "Delivery_Date": "2021-08-05T01:57:13",
        "Loading_Date": "2021-08-05T01:30:00",
        "Split_Load_Store": 0,
        "Driver_Name": "Jen Hawley",
        "Driver_Id": 7064,
        "Carrier_Id": 3003,
        "Carrier_Name": "United Petroleum Transport                        ",
        "Terminal_Id": 1634,
        "Terminal_Name": "Phillips66 - Wichita, KS North          ",
        "Vendor_Id": 11362,
        "Vendor_Name": "Phillips66 Contract                               ",
        "Tractor": "9999",
        "Trailer": "9999",
        "Bol_Detail": [
            {
                "EPA_Tank_id": 0,
                "Physical_Tanks": "1,2",
                "Product": "UNLEADED",
                "Pricing_Grade": 45,
                "Pricing_Grade_Name": "UNL 87 CONV 10% ETH",
                "Qt_Grade": 2,
                "Beg_Inches": "57.83|58.84",
                "End_Inches": "71.82|72.47",
                "Beg_Gallons": 19384,
                "End_Gallons": 25398,
                "Beg_Console": 19,
                "End_Console": 57,
                "Delivery_Gallons": 6014,
                "Sales_Gallons": 38,
                "Sales_During": 6014,
                "Gross": 6061,
                "Net": 6004,
                "Actual": 6052,
                "Variance": -9,
                "Date_Stamp": "2021-08-05T02:14:10"
            },
            {
                "EPA_Tank_id": 0,
                "Physical_Tanks": "3",
                "Product": "PREMIUM",
                "Pricing_Grade": 47,
                "Pricing_Grade_Name": "PRE 91 CONV 10% ETH",
                "Qt_Grade": 5,
                "Beg_Inches": "45.31",
                "End_Inches": "69.64",
                "Beg_Gallons": 3341,
                "End_Gallons": 5806,
                "Beg_Console": 0,
                "End_Console": 0,
                "Delivery_Gallons": 2465,
                "Sales_Gallons": 0,
                "Sales_During": 2465,
                "Gross": 2440,
                "Net": 2413,
                "Actual": 2465,
                "Variance": 25,
                "Date_Stamp": "2021-08-05T02:14:10"
            }
        ]
    },
    {
        "Store_Number": 366,
        "Bol_Number": "909076",
        "Delivery_Entry_ID": 2021080501,
        "Delivery_Date": "2021-08-05T01:57:13",
        "Loading_Date": "2021-08-05T01:30:00",
        "Split_Load_Store": 0,
        "Driver_Name": "Jen Hawley",
        "Driver_Id": 7064,
        "Carrier_Id": 3003,
        "Carrier_Name": "United Petroleum Transport                        ",
        "Terminal_Id": 1634,
        "Terminal_Name": "Phillips66 - Wichita, KS North          ",
        "Vendor_Id": 11362,
        "Vendor_Name": "Phillips66 Contract                               ",
        "Tractor": "9999",
        "Trailer": "9999",
        "Bol_Detail": [
            {
                "EPA_Tank_id": 0,
                "Physical_Tanks": "1,2",
                "Product": "UNLEADED",
                "Pricing_Grade": 45,
                "Pricing_Grade_Name": "UNL 87 CONV 10% ETH",
                "Qt_Grade": 2,
                "Beg_Inches": "57.83|58.84",
                "End_Inches": "71.82|72.47",
                "Beg_Gallons": 19384,
                "End_Gallons": 25398,
                "Beg_Console": 19,
                "End_Console": 57,
                "Delivery_Gallons": 6014,
                "Sales_Gallons": 38,
                "Sales_During": 6014,
                "Gross": 6061,
                "Net": 6004,
                "Actual": 6052,
                "Variance": -9,
                "Date_Stamp": "2021-08-05T02:14:10"
            },
            {
                "EPA_Tank_id": 0,
                "Physical_Tanks": "3",
                "Product": "PREMIUM",
                "Pricing_Grade": 47,
                "Pricing_Grade_Name": "PRE 91 CONV 10% ETH",
                "Qt_Grade": 5,
                "Beg_Inches": "45.31",
                "End_Inches": "69.64",
                "Beg_Gallons": 3341,
                "End_Gallons": 5806,
                "Beg_Console": 0,
                "End_Console": 0,
                "Delivery_Gallons": 2465,
                "Sales_Gallons": 0,
                "Sales_During": 2465,
                "Gross": 2440,
                "Net": 2413,
                "Actual": 2465,
                "Variance": 25,
                "Date_Stamp": "2021-08-05T02:14:10"
            }
        ]
    },
    {
        "Store_Number": 366,
        "Bol_Number": "742578",
        "Delivery_Entry_ID": 2021080601,
        "Delivery_Date": "2021-08-06T12:25:06",
        "Loading_Date": "2021-08-06T11:52:00",
        "Split_Load_Store": 0,
        "Driver_Name": "Doug Million",
        "Driver_Id": 302,
        "Carrier_Id": 3003,
        "Carrier_Name": "United Petroleum Transport                        ",
        "Terminal_Id": 153,
        "Terminal_Name": "Magellan - Valley Center, KS            ",
        "Vendor_Id": 11420,
        "Vendor_Name": "QT Fuels Inventory                                ",
        "Tractor": "2756",
        "Trailer": "1031",
        "Bol_Detail": [
            {
                "EPA_Tank_id": 0,
                "Physical_Tanks": "1,2",
                "Product": "UNLEADED",
                "Pricing_Grade": 45,
                "Pricing_Grade_Name": "UNL 87 CONV 10% ETH",
                "Qt_Grade": 2,
                "Beg_Inches": "47.01|47.22",
                "End_Inches": "62.74|63.12",
                "Beg_Gallons": 14473,
                "End_Gallons": 21404,
                "Beg_Console": 3017,
                "End_Console": 3126,
                "Delivery_Gallons": 6931,
                "Sales_Gallons": 109,
                "Sales_During": 6931,
                "Gross": 7004,
                "Net": 6924,
                "Actual": 7040,
                "Variance": 36,
                "Date_Stamp": "2021-08-06T12:46:21"
            },
            {
                "EPA_Tank_id": 0,
                "Physical_Tanks": "5",
                "Product": "UNL-NO-ETHANOL",
                "Pricing_Grade": 1,
                "Pricing_Grade_Name": "UNL 87 CONV NO ETH",
                "Qt_Grade": 1,
                "Beg_Inches": "19.3",
                "End_Inches": "35.23",
                "Beg_Gallons": 992,
                "End_Gallons": 2450,
                "Beg_Console": 128,
                "End_Console": 128,
                "Delivery_Gallons": 1458,
                "Sales_Gallons": 0,
                "Sales_During": 1458,
                "Gross": 1500,
                "Net": 1480,
                "Actual": 1458,
                "Variance": -42,
                "Date_Stamp": "2021-08-06T12:46:21"
            }
        ]
    },
    {
        "Store_Number": 366,
        "Bol_Number": "742578",
        "Delivery_Entry_ID": 2021080601,
        "Delivery_Date": "2021-08-06T12:25:06",
        "Loading_Date": "2021-08-06T11:52:00",
        "Split_Load_Store": 0,
        "Driver_Name": "Doug Million",
        "Driver_Id": 302,
        "Carrier_Id": 3003,
        "Carrier_Name": "United Petroleum Transport                        ",
        "Terminal_Id": 153,
        "Terminal_Name": "Magellan - Valley Center, KS            ",
        "Vendor_Id": 11420,
        "Vendor_Name": "QT Fuels Inventory                                ",
        "Tractor": "2756",
        "Trailer": "1031",
        "Bol_Detail": [
            {
                "EPA_Tank_id": 0,
                "Physical_Tanks": "1,2",
                "Product": "UNLEADED",
                "Pricing_Grade": 45,
                "Pricing_Grade_Name": "UNL 87 CONV 10% ETH",
                "Qt_Grade": 2,
                "Beg_Inches": "47.01|47.22",
                "End_Inches": "62.74|63.12",
                "Beg_Gallons": 14473,
                "End_Gallons": 21404,
                "Beg_Console": 3017,
                "End_Console": 3126,
                "Delivery_Gallons": 6931,
                "Sales_Gallons": 109,
                "Sales_During": 6931,
                "Gross": 7004,
                "Net": 6924,
                "Actual": 7040,
                "Variance": 36,
                "Date_Stamp": "2021-08-06T12:46:21"
            },
            {
                "EPA_Tank_id": 0,
                "Physical_Tanks": "5",
                "Product": "UNL-NO-ETHANOL",
                "Pricing_Grade": 1,
                "Pricing_Grade_Name": "UNL 87 CONV NO ETH",
                "Qt_Grade": 1,
                "Beg_Inches": "19.3",
                "End_Inches": "35.23",
                "Beg_Gallons": 992,
                "End_Gallons": 2450,
                "Beg_Console": 128,
                "End_Console": 128,
                "Delivery_Gallons": 1458,
                "Sales_Gallons": 0,
                "Sales_During": 1458,
                "Gross": 1500,
                "Net": 1480,
                "Actual": 1458,
                "Variance": -42,
                "Date_Stamp": "2021-08-06T12:46:21"
            }
        ]
    },
    {
        "Store_Number": 366,
        "Bol_Number": "742689",
        "Delivery_Entry_ID": 2021080701,
        "Delivery_Date": "2021-08-07T16:56:48",
        "Loading_Date": "2021-08-07T16:26:00",
        "Split_Load_Store": 0,
        "Driver_Name": "Doug Million",
        "Driver_Id": 302,
        "Carrier_Id": 3003,
        "Carrier_Name": "United Petroleum Transport                        ",
        "Terminal_Id": 153,
        "Terminal_Name": "Magellan - Valley Center, KS            ",
        "Vendor_Id": 11420,
        "Vendor_Name": "QT Fuels Inventory                                ",
        "Tractor": "2756",
        "Trailer": "1031",
        "Bol_Detail": [
            {
                "EPA_Tank_id": 0,
                "Physical_Tanks": "1,2",
                "Product": "UNLEADED",
                "Pricing_Grade": 45,
                "Pricing_Grade_Name": "UNL 87 CONV 10% ETH",
                "Qt_Grade": 2,
                "Beg_Inches": "38.81|39.39",
                "End_Inches": "55.05|55.63",
                "Beg_Gallons": 11126,
                "End_Gallons": 18056,
                "Beg_Console": 5088,
                "End_Console": 5182,
                "Delivery_Gallons": 6930,
                "Sales_Gallons": 94,
                "Sales_During": 6930,
                "Gross": 7004,
                "Net": 6892,
                "Actual": 7024,
                "Variance": 20,
                "Date_Stamp": "2021-08-07T17:14:45"
            },
            {
                "EPA_Tank_id": 0,
                "Physical_Tanks": "3",
                "Product": "PREMIUM",
                "Pricing_Grade": 47,
                "Pricing_Grade_Name": "PRE 91 CONV 10% ETH",
                "Qt_Grade": 5,
                "Beg_Inches": "34.24",
                "End_Inches": "49.52",
                "Beg_Gallons": 2284,
                "End_Gallons": 3762,
                "Beg_Console": 827,
                "End_Console": 856,
                "Delivery_Gallons": 1478,
                "Sales_Gallons": 29,
                "Sales_During": 1478,
                "Gross": 1500,
                "Net": 1470,
                "Actual": 1507,
                "Variance": 7,
                "Date_Stamp": "2021-08-07T17:14:45"
            }
        ]
    },
    {
        "Store_Number": 366,
        "Bol_Number": "742689",
        "Delivery_Entry_ID": 2021080701,
        "Delivery_Date": "2021-08-07T16:56:48",
        "Loading_Date": "2021-08-07T16:26:00",
        "Split_Load_Store": 0,
        "Driver_Name": "Doug Million",
        "Driver_Id": 302,
        "Carrier_Id": 3003,
        "Carrier_Name": "United Petroleum Transport                        ",
        "Terminal_Id": 153,
        "Terminal_Name": "Magellan - Valley Center, KS            ",
        "Vendor_Id": 11420,
        "Vendor_Name": "QT Fuels Inventory                                ",
        "Tractor": "2756",
        "Trailer": "1031",
        "Bol_Detail": [
            {
                "EPA_Tank_id": 0,
                "Physical_Tanks": "1,2",
                "Product": "UNLEADED",
                "Pricing_Grade": 45,
                "Pricing_Grade_Name": "UNL 87 CONV 10% ETH",
                "Qt_Grade": 2,
                "Beg_Inches": "38.81|39.39",
                "End_Inches": "55.05|55.63",
                "Beg_Gallons": 11126,
                "End_Gallons": 18056,
                "Beg_Console": 5088,
                "End_Console": 5182,
                "Delivery_Gallons": 6930,
                "Sales_Gallons": 94,
                "Sales_During": 6930,
                "Gross": 7004,
                "Net": 6892,
                "Actual": 7024,
                "Variance": 20,
                "Date_Stamp": "2021-08-07T17:14:45"
            },
            {
                "EPA_Tank_id": 0,
                "Physical_Tanks": "3",
                "Product": "PREMIUM",
                "Pricing_Grade": 47,
                "Pricing_Grade_Name": "PRE 91 CONV 10% ETH",
                "Qt_Grade": 5,
                "Beg_Inches": "34.24",
                "End_Inches": "49.52",
                "Beg_Gallons": 2284,
                "End_Gallons": 3762,
                "Beg_Console": 827,
                "End_Console": 856,
                "Delivery_Gallons": 1478,
                "Sales_Gallons": 29,
                "Sales_During": 1478,
                "Gross": 1500,
                "Net": 1470,
                "Actual": 1507,
                "Variance": 7,
                "Date_Stamp": "2021-08-07T17:14:45"
            }
        ]
    },
    {
        "Store_Number": 366,
        "Bol_Number": "742769",
        "Delivery_Entry_ID": 2021080901,
        "Delivery_Date": "2021-08-09T01:58:25",
        "Loading_Date": "2021-08-09T01:09:00",
        "Split_Load_Store": 0,
        "Driver_Name": "YLARIA FLORES",
        "Driver_Id": 8147,
        "Carrier_Id": 3003,
        "Carrier_Name": "United Petroleum Transport                        ",
        "Terminal_Id": 153,
        "Terminal_Name": "Magellan - Valley Center, KS            ",
        "Vendor_Id": 11420,
        "Vendor_Name": "QT Fuels Inventory                                ",
        "Tractor": "2811",
        "Trailer": "450",
        "Bol_Detail": [
            {
                "EPA_Tank_id": 0,
                "Physical_Tanks": "1,2",
                "Product": "UNLEADED",
                "Pricing_Grade": 45,
                "Pricing_Grade_Name": "UNL 87 CONV 10% ETH",
                "Qt_Grade": 2,
                "Beg_Inches": "32.91|33.64",
                "End_Inches": "52.35|47.88",
                "Beg_Gallons": 8838,
                "End_Gallons": 15770,
                "Beg_Console": 26,
                "End_Console": 61,
                "Delivery_Gallons": 6932,
                "Sales_Gallons": 35,
                "Sales_During": 6932,
                "Gross": 7006,
                "Net": 6927,
                "Actual": 6967,
                "Variance": -39,
                "Date_Stamp": "2021-08-09T02:34:44"
            },
            {
                "EPA_Tank_id": 0,
                "Physical_Tanks": "3",
                "Product": "PREMIUM",
                "Pricing_Grade": 47,
                "Pricing_Grade_Name": "PRE 91 CONV 10% ETH",
                "Qt_Grade": 5,
                "Beg_Inches": "31.07",
                "End_Inches": "46.69",
                "Beg_Gallons": 1998,
                "End_Gallons": 3479,
                "Beg_Console": 7,
                "End_Console": 27,
                "Delivery_Gallons": 1481,
                "Sales_Gallons": 20,
                "Sales_During": 1481,
                "Gross": 1500,
                "Net": 1483,
                "Actual": 1501,
                "Variance": 1,
                "Date_Stamp": "2021-08-09T02:34:44"
            }
        ]
    },
    {
        "Store_Number": 366,
        "Bol_Number": "742769",
        "Delivery_Entry_ID": 2021080901,
        "Delivery_Date": "2021-08-09T01:58:25",
        "Loading_Date": "2021-08-09T01:09:00",
        "Split_Load_Store": 0,
        "Driver_Name": "YLARIA FLORES",
        "Driver_Id": 8147,
        "Carrier_Id": 3003,
        "Carrier_Name": "United Petroleum Transport                        ",
        "Terminal_Id": 153,
        "Terminal_Name": "Magellan - Valley Center, KS            ",
        "Vendor_Id": 11420,
        "Vendor_Name": "QT Fuels Inventory                                ",
        "Tractor": "2811",
        "Trailer": "450",
        "Bol_Detail": [
            {
                "EPA_Tank_id": 0,
                "Physical_Tanks": "1,2",
                "Product": "UNLEADED",
                "Pricing_Grade": 45,
                "Pricing_Grade_Name": "UNL 87 CONV 10% ETH",
                "Qt_Grade": 2,
                "Beg_Inches": "32.91|33.64",
                "End_Inches": "52.35|47.88",
                "Beg_Gallons": 8838,
                "End_Gallons": 15770,
                "Beg_Console": 26,
                "End_Console": 61,
                "Delivery_Gallons": 6932,
                "Sales_Gallons": 35,
                "Sales_During": 6932,
                "Gross": 7006,
                "Net": 6927,
                "Actual": 6967,
                "Variance": -39,
                "Date_Stamp": "2021-08-09T02:34:44"
            },
            {
                "EPA_Tank_id": 0,
                "Physical_Tanks": "3",
                "Product": "PREMIUM",
                "Pricing_Grade": 47,
                "Pricing_Grade_Name": "PRE 91 CONV 10% ETH",
                "Qt_Grade": 5,
                "Beg_Inches": "31.07",
                "End_Inches": "46.69",
                "Beg_Gallons": 1998,
                "End_Gallons": 3479,
                "Beg_Console": 7,
                "End_Console": 27,
                "Delivery_Gallons": 1481,
                "Sales_Gallons": 20,
                "Sales_During": 1481,
                "Gross": 1500,
                "Net": 1483,
                "Actual": 1501,
                "Variance": 1,
                "Date_Stamp": "2021-08-09T02:34:44"
            }
        ]
    },
    {
        "Store_Number": 366,
        "Bol_Number": "742862",
        "Delivery_Entry_ID": 2021080902,
        "Delivery_Date": "2021-08-09T20:32:14",
        "Loading_Date": "2021-08-09T20:00:00",
        "Split_Load_Store": 0,
        "Driver_Name": "Jen Hawley",
        "Driver_Id": 7064,
        "Carrier_Id": 3003,
        "Carrier_Name": "United Petroleum Transport                        ",
        "Terminal_Id": 153,
        "Terminal_Name": "Magellan - Valley Center, KS            ",
        "Vendor_Id": 11420,
        "Vendor_Name": "QT Fuels Inventory                                ",
        "Tractor": "9999",
        "Trailer": "9999",
        "Bol_Detail": [
            {
                "EPA_Tank_id": 0,
                "Physical_Tanks": "1,2",
                "Product": "UNLEADED",
                "Pricing_Grade": 45,
                "Pricing_Grade_Name": "UNL 87 CONV 10% ETH",
                "Qt_Grade": 2,
                "Beg_Inches": "34.13|34.95",
                "End_Inches": "50.96|51.34",
                "Beg_Gallons": 9322,
                "End_Gallons": 16216,
                "Beg_Console": 6399,
                "End_Console": 6614,
                "Delivery_Gallons": 6894,
                "Sales_Gallons": 215,
                "Sales_During": 6894,
                "Gross": 7003,
                "Net": 6909,
                "Actual": 7109,
                "Variance": 106,
                "Date_Stamp": "2021-08-09T20:50:11"
            },
            {
                "EPA_Tank_id": 0,
                "Physical_Tanks": "3",
                "Product": "PREMIUM",
                "Pricing_Grade": 47,
                "Pricing_Grade_Name": "PRE 91 CONV 10% ETH",
                "Qt_Grade": 5,
                "Beg_Inches": "36.67",
                "End_Inches": "52.04",
                "Beg_Gallons": 2508,
                "End_Gallons": 4018,
                "Beg_Console": 845,
                "End_Console": 1000,
                "Delivery_Gallons": 1510,
                "Sales_Gallons": 155,
                "Sales_During": 1510,
                "Gross": 1504,
                "Net": 1480,
                "Actual": 1665,
                "Variance": 161,
                "Date_Stamp": "2021-08-09T20:50:11"
            }
        ]
    },
    {
        "Store_Number": 366,
        "Bol_Number": "742862",
        "Delivery_Entry_ID": 2021080902,
        "Delivery_Date": "2021-08-09T20:32:14",
        "Loading_Date": "2021-08-09T20:00:00",
        "Split_Load_Store": 0,
        "Driver_Name": "Jen Hawley",
        "Driver_Id": 7064,
        "Carrier_Id": 3003,
        "Carrier_Name": "United Petroleum Transport                        ",
        "Terminal_Id": 153,
        "Terminal_Name": "Magellan - Valley Center, KS            ",
        "Vendor_Id": 11420,
        "Vendor_Name": "QT Fuels Inventory                                ",
        "Tractor": "9999",
        "Trailer": "9999",
        "Bol_Detail": [
            {
                "EPA_Tank_id": 0,
                "Physical_Tanks": "1,2",
                "Product": "UNLEADED",
                "Pricing_Grade": 45,
                "Pricing_Grade_Name": "UNL 87 CONV 10% ETH",
                "Qt_Grade": 2,
                "Beg_Inches": "34.13|34.95",
                "End_Inches": "50.96|51.34",
                "Beg_Gallons": 9322,
                "End_Gallons": 16216,
                "Beg_Console": 6399,
                "End_Console": 6614,
                "Delivery_Gallons": 6894,
                "Sales_Gallons": 215,
                "Sales_During": 6894,
                "Gross": 7003,
                "Net": 6909,
                "Actual": 7109,
                "Variance": 106,
                "Date_Stamp": "2021-08-09T20:50:11"
            },
            {
                "EPA_Tank_id": 0,
                "Physical_Tanks": "3",
                "Product": "PREMIUM",
                "Pricing_Grade": 47,
                "Pricing_Grade_Name": "PRE 91 CONV 10% ETH",
                "Qt_Grade": 5,
                "Beg_Inches": "36.67",
                "End_Inches": "52.04",
                "Beg_Gallons": 2508,
                "End_Gallons": 4018,
                "Beg_Console": 845,
                "End_Console": 1000,
                "Delivery_Gallons": 1510,
                "Sales_Gallons": 155,
                "Sales_During": 1510,
                "Gross": 1504,
                "Net": 1480,
                "Actual": 1665,
                "Variance": 161,
                "Date_Stamp": "2021-08-09T20:50:11"
            }
        ]
    },
    {
        "Store_Number": 366,
        "Bol_Number": "742879",
        "Delivery_Entry_ID": 2021081001,
        "Delivery_Date": "2021-08-10T03:14:18",
        "Loading_Date": "2021-08-10T02:32:00",
        "Split_Load_Store": 0,
        "Driver_Name": "YLARIA FLORES",
        "Driver_Id": 8147,
        "Carrier_Id": 3003,
        "Carrier_Name": "United Petroleum Transport                        ",
        "Terminal_Id": 153,
        "Terminal_Name": "Magellan - Valley Center, KS            ",
        "Vendor_Id": 11420,
        "Vendor_Name": "QT Fuels Inventory                                ",
        "Tractor": "2811",
        "Trailer": "450",
        "Bol_Detail": [
            {
                "EPA_Tank_id": 0,
                "Physical_Tanks": "1,2",
                "Product": "UNLEADED",
                "Pricing_Grade": 45,
                "Pricing_Grade_Name": "UNL 87 CONV 10% ETH",
                "Qt_Grade": 2,
                "Beg_Inches": "49.19|49.77",
                "End_Inches": "74.23|63.88",
                "Beg_Gallons": 15490,
                "End_Gallons": 24053,
                "Beg_Console": 46,
                "End_Console": 46,
                "Delivery_Gallons": 8563,
                "Sales_Gallons": 0,
                "Sales_During": 8563,
                "Gross": 8503,
                "Net": 8397,
                "Actual": 8563,
                "Variance": 60,
                "Date_Stamp": "2021-08-10T03:48:21"
            }
        ]
    },
    {
        "Store_Number": 366,
        "Bol_Number": "909681",
        "Delivery_Entry_ID": 2021081101,
        "Delivery_Date": "2021-08-11T14:42:33",
        "Loading_Date": "2021-08-11T14:22:00",
        "Split_Load_Store": 0,
        "Driver_Name": "Dave Watts",
        "Driver_Id": 311,
        "Carrier_Id": 3003,
        "Carrier_Name": "United Petroleum Transport                        ",
        "Terminal_Id": 1634,
        "Terminal_Name": "Phillips66 - Wichita, KS North          ",
        "Vendor_Id": 11362,
        "Vendor_Name": "Phillips66 Contract                               ",
        "Tractor": "2747",
        "Trailer": "1027",
        "Bol_Detail": [
            {
                "EPA_Tank_id": 0,
                "Physical_Tanks": "1,2",
                "Product": "UNLEADED",
                "Pricing_Grade": 45,
                "Pricing_Grade_Name": "UNL 87 CONV 10% ETH",
                "Qt_Grade": 2,
                "Beg_Inches": "40.43|41.27",
                "End_Inches": "56.16|56.71",
                "Beg_Gallons": 11839,
                "End_Gallons": 18542,
                "Beg_Console": 3985,
                "End_Console": 4151,
                "Delivery_Gallons": 6703,
                "Sales_Gallons": 166,
                "Sales_During": 6703,
                "Gross": 6879,
                "Net": 6753,
                "Actual": 6869,
                "Variance": -10,
                "Date_Stamp": "2021-08-11T14:57:53"
            },
            {
                "EPA_Tank_id": 0,
                "Physical_Tanks": "3",
                "Product": "PREMIUM",
                "Pricing_Grade": 47,
                "Pricing_Grade_Name": "PRE 91 CONV 10% ETH",
                "Qt_Grade": 5,
                "Beg_Inches": "36.52",
                "End_Inches": "52.73",
                "Beg_Gallons": 2494,
                "End_Gallons": 4088,
                "Beg_Console": 433,
                "End_Console": 463,
                "Delivery_Gallons": 1594,
                "Sales_Gallons": 30,
                "Sales_During": 1594,
                "Gross": 1621,
                "Net": 1588,
                "Actual": 1624,
                "Variance": 3,
                "Date_Stamp": "2021-08-11T14:57:53"
            }
        ]
    },
    {
        "Store_Number": 366,
        "Bol_Number": "909681",
        "Delivery_Entry_ID": 2021081101,
        "Delivery_Date": "2021-08-11T14:42:33",
        "Loading_Date": "2021-08-11T14:22:00",
        "Split_Load_Store": 0,
        "Driver_Name": "Dave Watts",
        "Driver_Id": 311,
        "Carrier_Id": 3003,
        "Carrier_Name": "United Petroleum Transport                        ",
        "Terminal_Id": 1634,
        "Terminal_Name": "Phillips66 - Wichita, KS North          ",
        "Vendor_Id": 11362,
        "Vendor_Name": "Phillips66 Contract                               ",
        "Tractor": "2747",
        "Trailer": "1027",
        "Bol_Detail": [
            {
                "EPA_Tank_id": 0,
                "Physical_Tanks": "1,2",
                "Product": "UNLEADED",
                "Pricing_Grade": 45,
                "Pricing_Grade_Name": "UNL 87 CONV 10% ETH",
                "Qt_Grade": 2,
                "Beg_Inches": "40.43|41.27",
                "End_Inches": "56.16|56.71",
                "Beg_Gallons": 11839,
                "End_Gallons": 18542,
                "Beg_Console": 3985,
                "End_Console": 4151,
                "Delivery_Gallons": 6703,
                "Sales_Gallons": 166,
                "Sales_During": 6703,
                "Gross": 6879,
                "Net": 6753,
                "Actual": 6869,
                "Variance": -10,
                "Date_Stamp": "2021-08-11T14:57:53"
            },
            {
                "EPA_Tank_id": 0,
                "Physical_Tanks": "3",
                "Product": "PREMIUM",
                "Pricing_Grade": 47,
                "Pricing_Grade_Name": "PRE 91 CONV 10% ETH",
                "Qt_Grade": 5,
                "Beg_Inches": "36.52",
                "End_Inches": "52.73",
                "Beg_Gallons": 2494,
                "End_Gallons": 4088,
                "Beg_Console": 433,
                "End_Console": 463,
                "Delivery_Gallons": 1594,
                "Sales_Gallons": 30,
                "Sales_During": 1594,
                "Gross": 1621,
                "Net": 1588,
                "Actual": 1624,
                "Variance": 3,
                "Date_Stamp": "2021-08-11T14:57:53"
            }
        ]
    },
    {
        "Store_Number": 366,
        "Bol_Number": "909726",
        "Delivery_Entry_ID": 2021081201,
        "Delivery_Date": "2021-08-12T03:00:09",
        "Loading_Date": "2021-08-12T02:40:00",
        "Split_Load_Store": 0,
        "Driver_Name": "BRIAN KADAU",
        "Driver_Id": 7527,
        "Carrier_Id": 3003,
        "Carrier_Name": "United Petroleum Transport                        ",
        "Terminal_Id": 1634,
        "Terminal_Name": "Phillips66 - Wichita, KS North          ",
        "Vendor_Id": 11362,
        "Vendor_Name": "Phillips66 Contract                               ",
        "Tractor": "2811",
        "Trailer": "496",
        "Bol_Detail": [
            {
                "EPA_Tank_id": 0,
                "Physical_Tanks": "1,2",
                "Product": "UNLEADED",
                "Pricing_Grade": 45,
                "Pricing_Grade_Name": "UNL 87 CONV 10% ETH",
                "Qt_Grade": 2,
                "Beg_Inches": "46.84|47.63",
                "End_Inches": "66.39|67.12",
                "Beg_Gallons": 14521,
                "End_Gallons": 23074,
                "Beg_Console": 80,
                "End_Console": 80,
                "Delivery_Gallons": 8553,
                "Sales_Gallons": 0,
                "Sales_During": 8553,
                "Gross": 8504,
                "Net": 8392,
                "Actual": 8553,
                "Variance": 49,
                "Date_Stamp": "2021-08-12T03:19:04"
            }
        ]
    },
    {
        "Store_Number": 366,
        "Bol_Number": "743178",
        "Delivery_Entry_ID": 2021081202,
        "Delivery_Date": "2021-08-12T18:32:37",
        "Loading_Date": "2021-08-12T18:02:00",
        "Split_Load_Store": 0,
        "Driver_Name": "BRIAN KADAU",
        "Driver_Id": 7527,
        "Carrier_Id": 3003,
        "Carrier_Name": "United Petroleum Transport                        ",
        "Terminal_Id": 153,
        "Terminal_Name": "Magellan - Valley Center, KS            ",
        "Vendor_Id": 11420,
        "Vendor_Name": "QT Fuels Inventory                                ",
        "Tractor": "2756",
        "Trailer": "1031",
        "Bol_Detail": [
            {
                "EPA_Tank_id": 0,
                "Physical_Tanks": "1,2",
                "Product": "UNLEADED",
                "Pricing_Grade": 45,
                "Pricing_Grade_Name": "UNL 87 CONV 10% ETH",
                "Qt_Grade": 2,
                "Beg_Inches": "51.37|52.01",
                "End_Inches": "64.59|65.67",
                "Beg_Gallons": 16453,
                "End_Gallons": 22369,
                "Beg_Console": 6650,
                "End_Console": 6787,
                "Delivery_Gallons": 5916,
                "Sales_Gallons": 137,
                "Sales_During": 5916,
                "Gross": 6006,
                "Net": 5896,
                "Actual": 6053,
                "Variance": 47,
                "Date_Stamp": "2021-08-12T18:54:17"
            },
            {
                "EPA_Tank_id": 0,
                "Physical_Tanks": "5",
                "Product": "UNL-NO-ETHANOL",
                "Pricing_Grade": 1,
                "Pricing_Grade_Name": "UNL 87 CONV NO ETH",
                "Qt_Grade": 1,
                "Beg_Inches": "19.96",
                "End_Inches": "44.85",
                "Beg_Gallons": 1045,
                "End_Gallons": 3499,
                "Beg_Console": 253,
                "End_Console": 253,
                "Delivery_Gallons": 2454,
                "Sales_Gallons": 0,
                "Sales_During": 2454,
                "Gross": 2505,
                "Net": 2451,
                "Actual": 2454,
                "Variance": -51,
                "Date_Stamp": "2021-08-12T18:54:17"
            }
        ]
    },
    {
        "Store_Number": 366,
        "Bol_Number": "743178",
        "Delivery_Entry_ID": 2021081202,
        "Delivery_Date": "2021-08-12T18:32:37",
        "Loading_Date": "2021-08-12T18:02:00",
        "Split_Load_Store": 0,
        "Driver_Name": "BRIAN KADAU",
        "Driver_Id": 7527,
        "Carrier_Id": 3003,
        "Carrier_Name": "United Petroleum Transport                        ",
        "Terminal_Id": 153,
        "Terminal_Name": "Magellan - Valley Center, KS            ",
        "Vendor_Id": 11420,
        "Vendor_Name": "QT Fuels Inventory                                ",
        "Tractor": "2756",
        "Trailer": "1031",
        "Bol_Detail": [
            {
                "EPA_Tank_id": 0,
                "Physical_Tanks": "1,2",
                "Product": "UNLEADED",
                "Pricing_Grade": 45,
                "Pricing_Grade_Name": "UNL 87 CONV 10% ETH",
                "Qt_Grade": 2,
                "Beg_Inches": "51.37|52.01",
                "End_Inches": "64.59|65.67",
                "Beg_Gallons": 16453,
                "End_Gallons": 22369,
                "Beg_Console": 6650,
                "End_Console": 6787,
                "Delivery_Gallons": 5916,
                "Sales_Gallons": 137,
                "Sales_During": 5916,
                "Gross": 6006,
                "Net": 5896,
                "Actual": 6053,
                "Variance": 47,
                "Date_Stamp": "2021-08-12T18:54:17"
            },
            {
                "EPA_Tank_id": 0,
                "Physical_Tanks": "5",
                "Product": "UNL-NO-ETHANOL",
                "Pricing_Grade": 1,
                "Pricing_Grade_Name": "UNL 87 CONV NO ETH",
                "Qt_Grade": 1,
                "Beg_Inches": "19.96",
                "End_Inches": "44.85",
                "Beg_Gallons": 1045,
                "End_Gallons": 3499,
                "Beg_Console": 253,
                "End_Console": 253,
                "Delivery_Gallons": 2454,
                "Sales_Gallons": 0,
                "Sales_During": 2454,
                "Gross": 2505,
                "Net": 2451,
                "Actual": 2454,
                "Variance": -51,
                "Date_Stamp": "2021-08-12T18:54:17"
            }
        ]
    },
    {
        "Store_Number": 366,
        "Bol_Number": "909902",
        "Delivery_Entry_ID": 2021081301,
        "Delivery_Date": "2021-08-13T14:45:00",
        "Loading_Date": "2021-08-13T14:06:00",
        "Split_Load_Store": 0,
        "Driver_Name": "Dave Watts",
        "Driver_Id": 311,
        "Carrier_Id": 3003,
        "Carrier_Name": "United Petroleum Transport                        ",
        "Terminal_Id": 1634,
        "Terminal_Name": "Phillips66 - Wichita, KS North          ",
        "Vendor_Id": 11362,
        "Vendor_Name": "Phillips66 Contract                               ",
        "Tractor": "9999",
        "Trailer": "9999",
        "Bol_Detail": [
            {
                "EPA_Tank_id": 0,
                "Physical_Tanks": "1,2",
                "Product": "UNLEADED",
                "Pricing_Grade": 45,
                "Pricing_Grade_Name": "UNL 87 CONV 10% ETH",
                "Qt_Grade": 2,
                "Beg_Inches": "49.69|50.22",
                "End_Inches": "63.47|63.68",
                "Beg_Gallons": 15694,
                "End_Gallons": 21686,
                "Beg_Console": 4834,
                "End_Console": 4922,
                "Delivery_Gallons": 5992,
                "Sales_Gallons": 88,
                "Sales_During": 5992,
                "Gross": 6064,
                "Net": 6004,
                "Actual": 6081,
                "Variance": 17,
                "Date_Stamp": "2021-08-13T14:45:00"
            },
            {
                "EPA_Tank_id": 0,
                "Physical_Tanks": "3",
                "Product": "PREMIUM",
                "Pricing_Grade": 47,
                "Pricing_Grade_Name": "PRE 91 CONV 10% ETH",
                "Qt_Grade": 5,
                "Beg_Inches": "27.84",
                "End_Inches": "53.37",
                "Beg_Gallons": 1719,
                "End_Gallons": 4153,
                "Beg_Console": 485,
                "End_Console": 485,
                "Delivery_Gallons": 2434,
                "Sales_Gallons": 0,
                "Sales_During": 2434,
                "Gross": 2441,
                "Net": 2409,
                "Actual": 2434,
                "Variance": -7,
                "Date_Stamp": "2021-08-13T14:45:00"
            }
        ]
    },
    {
        "Store_Number": 366,
        "Bol_Number": "909902",
        "Delivery_Entry_ID": 2021081301,
        "Delivery_Date": "2021-08-13T14:45:00",
        "Loading_Date": "2021-08-13T14:06:00",
        "Split_Load_Store": 0,
        "Driver_Name": "Dave Watts",
        "Driver_Id": 311,
        "Carrier_Id": 3003,
        "Carrier_Name": "United Petroleum Transport                        ",
        "Terminal_Id": 1634,
        "Terminal_Name": "Phillips66 - Wichita, KS North          ",
        "Vendor_Id": 11362,
        "Vendor_Name": "Phillips66 Contract                               ",
        "Tractor": "9999",
        "Trailer": "9999",
        "Bol_Detail": [
            {
                "EPA_Tank_id": 0,
                "Physical_Tanks": "1,2",
                "Product": "UNLEADED",
                "Pricing_Grade": 45,
                "Pricing_Grade_Name": "UNL 87 CONV 10% ETH",
                "Qt_Grade": 2,
                "Beg_Inches": "49.69|50.22",
                "End_Inches": "63.47|63.68",
                "Beg_Gallons": 15694,
                "End_Gallons": 21686,
                "Beg_Console": 4834,
                "End_Console": 4922,
                "Delivery_Gallons": 5992,
                "Sales_Gallons": 88,
                "Sales_During": 5992,
                "Gross": 6064,
                "Net": 6004,
                "Actual": 6081,
                "Variance": 17,
                "Date_Stamp": "2021-08-13T14:45:00"
            },
            {
                "EPA_Tank_id": 0,
                "Physical_Tanks": "3",
                "Product": "PREMIUM",
                "Pricing_Grade": 47,
                "Pricing_Grade_Name": "PRE 91 CONV 10% ETH",
                "Qt_Grade": 5,
                "Beg_Inches": "27.84",
                "End_Inches": "53.37",
                "Beg_Gallons": 1719,
                "End_Gallons": 4153,
                "Beg_Console": 485,
                "End_Console": 485,
                "Delivery_Gallons": 2434,
                "Sales_Gallons": 0,
                "Sales_During": 2434,
                "Gross": 2441,
                "Net": 2409,
                "Actual": 2434,
                "Variance": -7,
                "Date_Stamp": "2021-08-13T14:45:00"
            }
        ]
    },
    {
        "Store_Number": 366,
        "Bol_Number": "910008",
        "Delivery_Entry_ID": 2021081401,
        "Delivery_Date": "2021-08-14T16:52:00",
        "Loading_Date": "2021-08-14T16:16:00",
        "Split_Load_Store": 0,
        "Driver_Name": "Jen Hawley",
        "Driver_Id": 7064,
        "Carrier_Id": 3003,
        "Carrier_Name": "United Petroleum Transport                        ",
        "Terminal_Id": 1634,
        "Terminal_Name": "Phillips66 - Wichita, KS North          ",
        "Vendor_Id": 11362,
        "Vendor_Name": "Phillips66 Contract                               ",
        "Tractor": "9999",
        "Trailer": "9999",
        "Bol_Detail": [
            {
                "EPA_Tank_id": 0,
                "Physical_Tanks": "1,2",
                "Product": "UNLEADED",
                "Pricing_Grade": 45,
                "Pricing_Grade_Name": "UNL 87 CONV 10% ETH",
                "Qt_Grade": 2,
                "Beg_Inches": "40.9|41.44",
                "End_Inches": "59.83|61.48",
                "Beg_Gallons": 11969,
                "End_Gallons": 20410,
                "Beg_Console": 5066,
                "End_Console": 5153,
                "Delivery_Gallons": 8441,
                "Sales_Gallons": 87,
                "Sales_During": 8441,
                "Gross": 8507,
                "Net": 8405,
                "Actual": 8527,
                "Variance": 20,
                "Date_Stamp": "2021-08-14T16:52:00"
            }
        ]
    },
    {
        "Store_Number": 366,
        "Bol_Number": "910078",
        "Delivery_Entry_ID": 2021081501,
        "Delivery_Date": "2021-08-15T14:38:10",
        "Loading_Date": "2021-08-15T14:16:00",
        "Split_Load_Store": 0,
        "Driver_Name": "Doug Million",
        "Driver_Id": 302,
        "Carrier_Id": 3003,
        "Carrier_Name": "United Petroleum Transport                        ",
        "Terminal_Id": 1634,
        "Terminal_Name": "Phillips66 - Wichita, KS North          ",
        "Vendor_Id": 11362,
        "Vendor_Name": "Phillips66 Contract                               ",
        "Tractor": "2756",
        "Trailer": "1031",
        "Bol_Detail": [
            {
                "EPA_Tank_id": 0,
                "Physical_Tanks": "1,2",
                "Product": "UNLEADED",
                "Pricing_Grade": 45,
                "Pricing_Grade_Name": "UNL 87 CONV 10% ETH",
                "Qt_Grade": 2,
                "Beg_Inches": "46.73|47.32",
                "End_Inches": "61.31|61.94",
                "Beg_Gallons": 14433,
                "End_Gallons": 20834,
                "Beg_Console": 3654,
                "End_Console": 3819,
                "Delivery_Gallons": 6401,
                "Sales_Gallons": 165,
                "Sales_During": 6401,
                "Gross": 6500,
                "Net": 6420,
                "Actual": 6566,
                "Variance": 66,
                "Date_Stamp": "2021-08-15T14:56:14"
            },
            {
                "EPA_Tank_id": 0,
                "Physical_Tanks": "3",
                "Product": "PREMIUM",
                "Pricing_Grade": 47,
                "Pricing_Grade_Name": "PRE 91 CONV 10% ETH",
                "Qt_Grade": 5,
                "Beg_Inches": "23.56",
                "End_Inches": "45.17",
                "Beg_Gallons": 1363,
                "End_Gallons": 3328,
                "Beg_Console": 744,
                "End_Console": 781,
                "Delivery_Gallons": 1965,
                "Sales_Gallons": 37,
                "Sales_During": 1965,
                "Gross": 2001,
                "Net": 1968,
                "Actual": 2002,
                "Variance": 1,
                "Date_Stamp": "2021-08-15T14:56:14"
            }
        ]
    },
    {
        "Store_Number": 366,
        "Bol_Number": "910078",
        "Delivery_Entry_ID": 2021081501,
        "Delivery_Date": "2021-08-15T14:38:10",
        "Loading_Date": "2021-08-15T14:16:00",
        "Split_Load_Store": 0,
        "Driver_Name": "Doug Million",
        "Driver_Id": 302,
        "Carrier_Id": 3003,
        "Carrier_Name": "United Petroleum Transport                        ",
        "Terminal_Id": 1634,
        "Terminal_Name": "Phillips66 - Wichita, KS North          ",
        "Vendor_Id": 11362,
        "Vendor_Name": "Phillips66 Contract                               ",
        "Tractor": "2756",
        "Trailer": "1031",
        "Bol_Detail": [
            {
                "EPA_Tank_id": 0,
                "Physical_Tanks": "1,2",
                "Product": "UNLEADED",
                "Pricing_Grade": 45,
                "Pricing_Grade_Name": "UNL 87 CONV 10% ETH",
                "Qt_Grade": 2,
                "Beg_Inches": "46.73|47.32",
                "End_Inches": "61.31|61.94",
                "Beg_Gallons": 14433,
                "End_Gallons": 20834,
                "Beg_Console": 3654,
                "End_Console": 3819,
                "Delivery_Gallons": 6401,
                "Sales_Gallons": 165,
                "Sales_During": 6401,
                "Gross": 6500,
                "Net": 6420,
                "Actual": 6566,
                "Variance": 66,
                "Date_Stamp": "2021-08-15T14:56:14"
            },
            {
                "EPA_Tank_id": 0,
                "Physical_Tanks": "3",
                "Product": "PREMIUM",
                "Pricing_Grade": 47,
                "Pricing_Grade_Name": "PRE 91 CONV 10% ETH",
                "Qt_Grade": 5,
                "Beg_Inches": "23.56",
                "End_Inches": "45.17",
                "Beg_Gallons": 1363,
                "End_Gallons": 3328,
                "Beg_Console": 744,
                "End_Console": 781,
                "Delivery_Gallons": 1965,
                "Sales_Gallons": 37,
                "Sales_During": 1965,
                "Gross": 2001,
                "Net": 1968,
                "Actual": 2002,
                "Variance": 1,
                "Date_Stamp": "2021-08-15T14:56:14"
            }
        ]
    },
    {
        "Store_Number": 366,
        "Bol_Number": "743446",
        "Delivery_Entry_ID": 2021081601,
        "Delivery_Date": "2021-08-16T11:50:00",
        "Loading_Date": "2021-08-16T10:51:00",
        "Split_Load_Store": 0,
        "Driver_Name": "Dave Watts",
        "Driver_Id": 311,
        "Carrier_Id": 3003,
        "Carrier_Name": "United Petroleum Transport                        ",
        "Terminal_Id": 153,
        "Terminal_Name": "Magellan - Valley Center, KS            ",
        "Vendor_Id": 11420,
        "Vendor_Name": "QT Fuels Inventory                                ",
        "Tractor": "9999",
        "Trailer": "9999",
        "Bol_Detail": [
            {
                "EPA_Tank_id": 0,
                "Physical_Tanks": "4",
                "Product": "DIESEL-AUTO",
                "Pricing_Grade": 8,
                "Pricing_Grade_Name": "ULSD #2 CLEAR - DIESEL",
                "Qt_Grade": 13,
                "Beg_Inches": "14.61",
                "End_Inches": "63.03",
                "Beg_Gallons": 1192,
                "End_Gallons": 8686,
                "Beg_Console": 397,
                "End_Console": 397,
                "Delivery_Gallons": 7494,
                "Sales_Gallons": 0,
                "Sales_During": 7494,
                "Gross": 7500,
                "Net": 7434,
                "Actual": 7494,
                "Variance": -6,
                "Date_Stamp": "2021-08-16T11:50:00"
            }
        ]
    },
    {
        "Store_Number": 366,
        "Bol_Number": "910202",
        "Delivery_Entry_ID": 2021081701,
        "Delivery_Date": "2021-08-17T06:26:57",
        "Loading_Date": "2021-08-17T05:53:00",
        "Split_Load_Store": 0,
        "Driver_Name": "David Felton",
        "Driver_Id": 7616,
        "Carrier_Id": 3003,
        "Carrier_Name": "United Petroleum Transport                        ",
        "Terminal_Id": 1634,
        "Terminal_Name": "Phillips66 - Wichita, KS North          ",
        "Vendor_Id": 11362,
        "Vendor_Name": "Phillips66 Contract                               ",
        "Tractor": "9999",
        "Trailer": "9999",
        "Bol_Detail": [
            {
                "EPA_Tank_id": 0,
                "Physical_Tanks": "1,2",
                "Product": "UNLEADED",
                "Pricing_Grade": 45,
                "Pricing_Grade_Name": "UNL 87 CONV 10% ETH",
                "Qt_Grade": 2,
                "Beg_Inches": "33.79|34.34",
                "End_Inches": "48.06|53.04",
                "Beg_Gallons": 9139,
                "End_Gallons": 15959,
                "Beg_Console": 399,
                "End_Console": 537,
                "Delivery_Gallons": 6820,
                "Sales_Gallons": 138,
                "Sales_During": 6820,
                "Gross": 6999,
                "Net": 6938,
                "Actual": 6958,
                "Variance": -41,
                "Date_Stamp": "2021-08-17T06:46:00"
            },
            {
                "EPA_Tank_id": 0,
                "Physical_Tanks": "3",
                "Product": "PREMIUM",
                "Pricing_Grade": 47,
                "Pricing_Grade_Name": "PRE 91 CONV 10% ETH",
                "Qt_Grade": 5,
                "Beg_Inches": "29.03",
                "End_Inches": "45.02",
                "Beg_Gallons": 1820,
                "End_Gallons": 3313,
                "Beg_Console": 10,
                "End_Console": 48,
                "Delivery_Gallons": 1493,
                "Sales_Gallons": 38,
                "Sales_During": 1493,
                "Gross": 1501,
                "Net": 1488,
                "Actual": 1531,
                "Variance": 30,
                "Date_Stamp": "2021-08-17T06:46:00"
            }
        ]
    },
    {
        "Store_Number": 366,
        "Bol_Number": "910202",
        "Delivery_Entry_ID": 2021081701,
        "Delivery_Date": "2021-08-17T06:26:57",
        "Loading_Date": "2021-08-17T05:53:00",
        "Split_Load_Store": 0,
        "Driver_Name": "David Felton",
        "Driver_Id": 7616,
        "Carrier_Id": 3003,
        "Carrier_Name": "United Petroleum Transport                        ",
        "Terminal_Id": 1634,
        "Terminal_Name": "Phillips66 - Wichita, KS North          ",
        "Vendor_Id": 11362,
        "Vendor_Name": "Phillips66 Contract                               ",
        "Tractor": "9999",
        "Trailer": "9999",
        "Bol_Detail": [
            {
                "EPA_Tank_id": 0,
                "Physical_Tanks": "1,2",
                "Product": "UNLEADED",
                "Pricing_Grade": 45,
                "Pricing_Grade_Name": "UNL 87 CONV 10% ETH",
                "Qt_Grade": 2,
                "Beg_Inches": "33.79|34.34",
                "End_Inches": "48.06|53.04",
                "Beg_Gallons": 9139,
                "End_Gallons": 15959,
                "Beg_Console": 399,
                "End_Console": 537,
                "Delivery_Gallons": 6820,
                "Sales_Gallons": 138,
                "Sales_During": 6820,
                "Gross": 6999,
                "Net": 6938,
                "Actual": 6958,
                "Variance": -41,
                "Date_Stamp": "2021-08-17T06:46:00"
            },
            {
                "EPA_Tank_id": 0,
                "Physical_Tanks": "3",
                "Product": "PREMIUM",
                "Pricing_Grade": 47,
                "Pricing_Grade_Name": "PRE 91 CONV 10% ETH",
                "Qt_Grade": 5,
                "Beg_Inches": "29.03",
                "End_Inches": "45.02",
                "Beg_Gallons": 1820,
                "End_Gallons": 3313,
                "Beg_Console": 10,
                "End_Console": 48,
                "Delivery_Gallons": 1493,
                "Sales_Gallons": 38,
                "Sales_During": 1493,
                "Gross": 1501,
                "Net": 1488,
                "Actual": 1531,
                "Variance": 30,
                "Date_Stamp": "2021-08-17T06:46:00"
            }
        ]
    },
    {
        "Store_Number": 366,
        "Bol_Number": "910266",
        "Delivery_Entry_ID": 2021081702,
        "Delivery_Date": "2021-08-17T16:28:03",
        "Loading_Date": "2021-08-17T16:04:00",
        "Split_Load_Store": 0,
        "Driver_Name": "Doug Million",
        "Driver_Id": 302,
        "Carrier_Id": 3003,
        "Carrier_Name": "United Petroleum Transport                        ",
        "Terminal_Id": 1634,
        "Terminal_Name": "Phillips66 - Wichita, KS North          ",
        "Vendor_Id": 11362,
        "Vendor_Name": "Phillips66 Contract                               ",
        "Tractor": "2756",
        "Trailer": "1031",
        "Bol_Detail": [
            {
                "EPA_Tank_id": 0,
                "Physical_Tanks": "1,2",
                "Product": "UNLEADED",
                "Pricing_Grade": 45,
                "Pricing_Grade_Name": "UNL 87 CONV 10% ETH",
                "Qt_Grade": 2,
                "Beg_Inches": "39.04|39.78",
                "End_Inches": "58.66|59.47",
                "Beg_Gallons": 11252,
                "End_Gallons": 19707,
                "Beg_Console": 5276,
                "End_Console": 5367,
                "Delivery_Gallons": 8455,
                "Sales_Gallons": 91,
                "Sales_During": 8455,
                "Gross": 8500,
                "Net": 8395,
                "Actual": 8546,
                "Variance": 46,
                "Date_Stamp": "2021-08-17T16:47:07"
            }
        ]
    },
    {
        "Store_Number": 366,
        "Bol_Number": "910326",
        "Delivery_Entry_ID": 2021081801,
        "Delivery_Date": "2021-08-18T07:50:55",
        "Loading_Date": "2021-08-18T07:31:00",
        "Split_Load_Store": 0,
        "Driver_Name": "Jeremy Dodd",
        "Driver_Id": 7211,
        "Carrier_Id": 3003,
        "Carrier_Name": "United Petroleum Transport                        ",
        "Terminal_Id": 1634,
        "Terminal_Name": "Phillips66 - Wichita, KS North          ",
        "Vendor_Id": 11362,
        "Vendor_Name": "Phillips66 Contract                               ",
        "Tractor": "2798",
        "Trailer": "968",
        "Bol_Detail": [
            {
                "EPA_Tank_id": 0,
                "Physical_Tanks": "1,2",
                "Product": "UNLEADED",
                "Pricing_Grade": 45,
                "Pricing_Grade_Name": "UNL 87 CONV 10% ETH",
                "Qt_Grade": 2,
                "Beg_Inches": "50.38|51.08",
                "End_Inches": "63.95|66.65",
                "Beg_Gallons": 16035,
                "End_Gallons": 22441,
                "Beg_Console": 930,
                "End_Console": 1038,
                "Delivery_Gallons": 6406,
                "Sales_Gallons": 108,
                "Sales_During": 6406,
                "Gross": 6499,
                "Net": 6433,
                "Actual": 6514,
                "Variance": 15,
                "Date_Stamp": "2021-08-18T08:07:14"
            },
            {
                "EPA_Tank_id": 0,
                "Physical_Tanks": "3",
                "Product": "PREMIUM",
                "Pricing_Grade": 47,
                "Pricing_Grade_Name": "PRE 91 CONV 10% ETH",
                "Qt_Grade": 5,
                "Beg_Inches": "32.66",
                "End_Inches": "52.69",
                "Beg_Gallons": 2141,
                "End_Gallons": 4084,
                "Beg_Console": 123,
                "End_Console": 134,
                "Delivery_Gallons": 1943,
                "Sales_Gallons": 11,
                "Sales_During": 1943,
                "Gross": 1940,
                "Net": 1918,
                "Actual": 1954,
                "Variance": 14,
                "Date_Stamp": "2021-08-18T08:07:14"
            }
        ]
    },
    {
        "Store_Number": 366,
        "Bol_Number": "910326",
        "Delivery_Entry_ID": 2021081801,
        "Delivery_Date": "2021-08-18T07:50:55",
        "Loading_Date": "2021-08-18T07:31:00",
        "Split_Load_Store": 0,
        "Driver_Name": "Jeremy Dodd",
        "Driver_Id": 7211,
        "Carrier_Id": 3003,
        "Carrier_Name": "United Petroleum Transport                        ",
        "Terminal_Id": 1634,
        "Terminal_Name": "Phillips66 - Wichita, KS North          ",
        "Vendor_Id": 11362,
        "Vendor_Name": "Phillips66 Contract                               ",
        "Tractor": "2798",
        "Trailer": "968",
        "Bol_Detail": [
            {
                "EPA_Tank_id": 0,
                "Physical_Tanks": "1,2",
                "Product": "UNLEADED",
                "Pricing_Grade": 45,
                "Pricing_Grade_Name": "UNL 87 CONV 10% ETH",
                "Qt_Grade": 2,
                "Beg_Inches": "50.38|51.08",
                "End_Inches": "63.95|66.65",
                "Beg_Gallons": 16035,
                "End_Gallons": 22441,
                "Beg_Console": 930,
                "End_Console": 1038,
                "Delivery_Gallons": 6406,
                "Sales_Gallons": 108,
                "Sales_During": 6406,
                "Gross": 6499,
                "Net": 6433,
                "Actual": 6514,
                "Variance": 15,
                "Date_Stamp": "2021-08-18T08:07:14"
            },
            {
                "EPA_Tank_id": 0,
                "Physical_Tanks": "3",
                "Product": "PREMIUM",
                "Pricing_Grade": 47,
                "Pricing_Grade_Name": "PRE 91 CONV 10% ETH",
                "Qt_Grade": 5,
                "Beg_Inches": "32.66",
                "End_Inches": "52.69",
                "Beg_Gallons": 2141,
                "End_Gallons": 4084,
                "Beg_Console": 123,
                "End_Console": 134,
                "Delivery_Gallons": 1943,
                "Sales_Gallons": 11,
                "Sales_During": 1943,
                "Gross": 1940,
                "Net": 1918,
                "Actual": 1954,
                "Variance": 14,
                "Date_Stamp": "2021-08-18T08:07:14"
            }
        ]
    },
    {
        "Store_Number": 366,
        "Bol_Number": "910377",
        "Delivery_Entry_ID": 2021081802,
        "Delivery_Date": "2021-08-18T15:35:07",
        "Loading_Date": "2021-08-18T15:12:00",
        "Split_Load_Store": 0,
        "Driver_Name": "Doug Million",
        "Driver_Id": 302,
        "Carrier_Id": 3003,
        "Carrier_Name": "United Petroleum Transport                        ",
        "Terminal_Id": 1634,
        "Terminal_Name": "Phillips66 - Wichita, KS North          ",
        "Vendor_Id": 11362,
        "Vendor_Name": "Phillips66 Contract                               ",
        "Tractor": "2756",
        "Trailer": "1031",
        "Bol_Detail": [
            {
                "EPA_Tank_id": 0,
                "Physical_Tanks": "1,2",
                "Product": "UNLEADED",
                "Pricing_Grade": 45,
                "Pricing_Grade_Name": "UNL 87 CONV 10% ETH",
                "Qt_Grade": 2,
                "Beg_Inches": "57.12|57.49",
                "End_Inches": "76.29|76.62",
                "Beg_Gallons": 18926,
                "End_Gallons": 27214,
                "Beg_Console": 4561,
                "End_Console": 4777,
                "Delivery_Gallons": 8288,
                "Sales_Gallons": 216,
                "Sales_During": 8288,
                "Gross": 8500,
                "Net": 8403,
                "Actual": 8504,
                "Variance": 4,
                "Date_Stamp": "2021-08-18T15:55:32"
            }
        ]
    },
    {
        "Store_Number": 366,
        "Bol_Number": "743747",
        "Delivery_Entry_ID": 2021081901,
        "Delivery_Date": "2021-08-19T13:13:23",
        "Loading_Date": "2021-08-19T12:18:00",
        "Split_Load_Store": 0,
        "Driver_Name": "ramiro munoz",
        "Driver_Id": 9999,
        "Carrier_Id": 3003,
        "Carrier_Name": "United Petroleum Transport                        ",
        "Terminal_Id": 153,
        "Terminal_Name": "Magellan - Valley Center, KS            ",
        "Vendor_Id": 11420,
        "Vendor_Name": "QT Fuels Inventory                                ",
        "Tractor": "2738",
        "Trailer": "882",
        "Bol_Detail": [
            {
                "EPA_Tank_id": 0,
                "Physical_Tanks": "1,2",
                "Product": "UNLEADED",
                "Pricing_Grade": 45,
                "Pricing_Grade_Name": "UNL 87 CONV 10% ETH",
                "Qt_Grade": 2,
                "Beg_Inches": "60.4|60.96",
                "End_Inches": "80.28|79.55",
                "Beg_Gallons": 20420,
                "End_Gallons": 28634,
                "Beg_Console": 3517,
                "End_Console": 3866,
                "Delivery_Gallons": 8214,
                "Sales_Gallons": 349,
                "Sales_During": 8214,
                "Gross": 8505,
                "Net": 8411,
                "Actual": 8563,
                "Variance": 58,
                "Date_Stamp": "2021-08-19T13:52:21"
            }
        ]
    },
    {
        "Store_Number": 366,
        "Bol_Number": "743825",
        "Delivery_Entry_ID": 2021082001,
        "Delivery_Date": "2021-08-20T06:28:00",
        "Loading_Date": "2021-08-20T05:43:00",
        "Split_Load_Store": 0,
        "Driver_Name": "David Felton",
        "Driver_Id": 7616,
        "Carrier_Id": 3003,
        "Carrier_Name": "United Petroleum Transport                        ",
        "Terminal_Id": 153,
        "Terminal_Name": "Magellan - Valley Center, KS            ",
        "Vendor_Id": 11420,
        "Vendor_Name": "QT Fuels Inventory                                ",
        "Tractor": "9999",
        "Trailer": "9999",
        "Bol_Detail": [
            {
                "EPA_Tank_id": 0,
                "Physical_Tanks": "1,2",
                "Product": "UNLEADED",
                "Pricing_Grade": 45,
                "Pricing_Grade_Name": "UNL 87 CONV 10% ETH",
                "Qt_Grade": 2,
                "Beg_Inches": "67.89|68.94",
                "End_Inches": "82.82|88.01",
                "Beg_Gallons": 23795,
                "End_Gallons": 30794,
                "Beg_Console": 459,
                "End_Console": 521,
                "Delivery_Gallons": 6999,
                "Sales_Gallons": 62,
                "Sales_During": 6999,
                "Gross": 7003,
                "Net": 6933,
                "Actual": 7061,
                "Variance": 58,
                "Date_Stamp": "2021-08-20T06:28:00"
            },
            {
                "EPA_Tank_id": 0,
                "Physical_Tanks": "3",
                "Product": "PREMIUM",
                "Pricing_Grade": 47,
                "Pricing_Grade_Name": "PRE 91 CONV 10% ETH",
                "Qt_Grade": 5,
                "Beg_Inches": "30.09",
                "End_Inches": "45.99",
                "Beg_Gallons": 1912,
                "End_Gallons": 3408,
                "Beg_Console": 28,
                "End_Console": 28,
                "Delivery_Gallons": 1496,
                "Sales_Gallons": 0,
                "Sales_During": 1496,
                "Gross": 1500,
                "Net": 1485,
                "Actual": 1496,
                "Variance": -4,
                "Date_Stamp": "2021-08-20T06:28:00"
            }
        ]
    },
    {
        "Store_Number": 366,
        "Bol_Number": "743825",
        "Delivery_Entry_ID": 2021082001,
        "Delivery_Date": "2021-08-20T06:28:00",
        "Loading_Date": "2021-08-20T05:43:00",
        "Split_Load_Store": 0,
        "Driver_Name": "David Felton",
        "Driver_Id": 7616,
        "Carrier_Id": 3003,
        "Carrier_Name": "United Petroleum Transport                        ",
        "Terminal_Id": 153,
        "Terminal_Name": "Magellan - Valley Center, KS            ",
        "Vendor_Id": 11420,
        "Vendor_Name": "QT Fuels Inventory                                ",
        "Tractor": "9999",
        "Trailer": "9999",
        "Bol_Detail": [
            {
                "EPA_Tank_id": 0,
                "Physical_Tanks": "1,2",
                "Product": "UNLEADED",
                "Pricing_Grade": 45,
                "Pricing_Grade_Name": "UNL 87 CONV 10% ETH",
                "Qt_Grade": 2,
                "Beg_Inches": "67.89|68.94",
                "End_Inches": "82.82|88.01",
                "Beg_Gallons": 23795,
                "End_Gallons": 30794,
                "Beg_Console": 459,
                "End_Console": 521,
                "Delivery_Gallons": 6999,
                "Sales_Gallons": 62,
                "Sales_During": 6999,
                "Gross": 7003,
                "Net": 6933,
                "Actual": 7061,
                "Variance": 58,
                "Date_Stamp": "2021-08-20T06:28:00"
            },
            {
                "EPA_Tank_id": 0,
                "Physical_Tanks": "3",
                "Product": "PREMIUM",
                "Pricing_Grade": 47,
                "Pricing_Grade_Name": "PRE 91 CONV 10% ETH",
                "Qt_Grade": 5,
                "Beg_Inches": "30.09",
                "End_Inches": "45.99",
                "Beg_Gallons": 1912,
                "End_Gallons": 3408,
                "Beg_Console": 28,
                "End_Console": 28,
                "Delivery_Gallons": 1496,
                "Sales_Gallons": 0,
                "Sales_During": 1496,
                "Gross": 1500,
                "Net": 1485,
                "Actual": 1496,
                "Variance": -4,
                "Date_Stamp": "2021-08-20T06:28:00"
            }
        ]
    }
];

bolDetail.forEach(function (obj) {
  db.collection('bolDetail').add( obj
  ).then(function (docRef) {
    console.log('Document written with ID: ', docRef.id);
  })
    .catch(function (error) {
      console.error('Error adding document: ', error);
    });
});
